In [1]:
import torch.nn as nn
from torch.optim import lr_scheduler
import torch
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

import torchvision
import torchvision.transforms as transforms

import torch.nn.functional as F

In [39]:

# initial Parameters
num_of_rows = 300
lr = 0.0004
gamma_lr_scheduler = 0.1 
weight_decay = 1e-4
criterion = nn.MSELoss()
optimizer = torch.optim.Adam
num_epochs =2500
criterion_name = "MSE_LOSS_"
optimizer_name = "ADAM_opt"
filename = criterion_name+ optimizer_name+".png"
grad_norm_name = "_grad_norm_name1_2.png"
result_folder_name = "result3/"

In [38]:

# train_dataset = torchvision.datasets.MNIST(root='./data/', train=True,
#                                  transform=torchvision.transforms.ToTensor(),
#                                  target_transform=torchvision.transforms.Compose([
#                                  lambda x:torch.LongTensor([x]), # or just torch.tensor
#                                  lambda x:F.one_hot(x,10)]),
#                                  download=True)

In [37]:
# train_dataset = torchvision.datasets.MNIST(root='./data', 
#                                            train=True, 
#                                            transform=transforms.Compose([
#                                                 transforms.Resize((32,32)),
#                                                 transforms.ToTensor(),
#                                                 transforms.Normalize((0.1307,), (0.3081,))
#                                                 ]),
#                                            target_transform=torchvision.transforms.Compose([
#                                                              lambda x:torch.LongTensor([x]), # or just torch.tensor
#                                                              lambda x:F.one_hot(x,10)]),
#                                            download=True,
#                                           )


# test_dataset = torchvision.datasets.MNIST(root='./data', 
#                                           train=False, 
#                                           transform=transforms.Compose([
#                                                 transforms.Resize((32, 32)),
#                                                 transforms.ToTensor(),
#                                                 transforms.Normalize((0.1307,), (0.3081,))
#                                                 ]),
#                                           target_transform=torchvision.transforms.Compose([
#                                                              lambda x:torch.LongTensor([x]), # or just torch.tensor
#                                                              lambda x:F.one_hot(x,10)]),
#                                          )

In [35]:
# type(train_dataset),len(train_dataset),dir(train_dataset)

In [28]:
# dir(test_dataset)

In [30]:
# len(train_dataset.train_labels)

In [29]:
# print("Size of:")
# print("- Training-set:\t\t{}".format(len(train_dataset.train_labels)))
# print("- Test-set:\t\t{}".format(len(test_dataset.test_labels)))
# print("- Validation-set:\t{}".format(len(data.validation.labels)))

In [31]:
# data_test_cls = np.argmax(train_dataset.train_labels)
# data_test_cls

In [32]:
# img_size = 32
# img_size_flat = img_size * img_size
# img_shape = (img_size, img_size)
# num_channels = 1
# num_classes = 10

In [33]:
# def pow_adder_reducer(x, y):
#     return (2 * x.pow(2) + 3 * y.pow(2)).sum()
# inputs = (torch.rand(2), torch.rand(2))

In [34]:
# inputs

In [26]:
torch.autograd.functional.hessian(pow_adder_reducer, inputs)

((tensor([[4., 0.],
          [0., 4.]]),
  tensor([[0., 0.],
          [0., 0.]])),
 (tensor([[0., 0.],
          [0., 0.]]),
  tensor([[6., 0.],
          [0., 6.]])))